apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-config
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  SYSTEM_URL	: {{ .Values.base_url | quote }}
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: DocuSign
  PRODUCT_NAME: DocuSign
  APP_KIND: rest-with-apikey
  API_DESCRIPTION: "APIs for DocuSign"
  API_SPECIFICATION_URL: https://raw.githubusercontent.com/docusign/eSign-OpenAPI-Specification/master/esignature.rest.swagger-v2.json
