apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: docusign-event-gw
  name: docusign-event-gw
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: docusign-event-gw
  type: ClusterIP
status:
  loadBalancer: {}
